import type { NextPage } from "next";
import Head from "next/head";
// import Image from "next/image";
import styles from "../styles/Home.module.css";

import Hero from "../modules/hero";
import About from "../modules/about";
import Contact from "../modules/contact";
import Products from "../modules/products";
import Footer from "../modules/footer";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <About />
        <Products />
        <Contact />
      </main>
    <Footer />
    </div>
  );
};

export default Home;
